= Fulcro RAD Demo

This is a demo repository for Fulcro RAD. It includes a shared source directory of files that would be
common to any project, and then separate source directories that have specific files that would be
needed to work with specific back-end technologies (currently SQL and Datomic).

IMPORTANT: Login is `tony@example.com` with password `letmein`.

== Status

The SQL version has some known bugs. If you want to play with RAD, use the Datomic database adapter for now.

WARNING: The API is *not* stable. While in Alpha *there will be breaking changes*. I will try to minimize these,
but this library is still in the design phases, so don't use it for "real stuff" unless you can tolerate that
instability on top of the alpha status.

== Running From Source

The *very* active development I'm doing makes changes to 5 projects at once (Fulcro, Fulcro RAD, Fulcro RAD Datomic,
Fulcro RAD SQL, and this demo). I do not guarantee I will keep everything in sync as far as versions in the deps
file go.  I personally set the following in my top-level `~/.clojure/deps.edn`:

[source]
-----
{:aliases {:f3-dev    {:override-deps {com.fulcrologic/fulcro {:local/root "/Users/tonykay/fulcrologic/fulcro"
                                                               :exclusions [com.taoensso/sente]}}}
           :rad-dev   {:override-deps {com.fulcrologic/fulcro-rad                 {:local/root "/Users/username/fulcrologic/fulcro-rad"}
                                       com.fulcrologic/fulcro-rad-sql             {:local/root "/Users/username/fulcrologic/fulcro-rad-sql"}
                                       com.fulcrologic/fulcro-rad-semantic-ui     {:local/root "/Users/username/fulcrologic/fulcro-rad-semantic-ui"}
                                       com.fulcrologic/fulcro-rad-datomic         {:local/root "/Users/username/fulcrologic/fulcro-rad-datomic"
                                                                                   :exclusions [com.datomic/datomic-free]}}}}}
-----

so that in IntelliJ (or at the command line) I can work from local sources for all of them.  I try to remember to push SNAPSHOTS
daily, but if I forget and you see some missing symbol error or things are broken, that is almost certainly why.

Running shadow and clj would look like this from the command line:

[source, bash]
-----
# in one terminal
$ shadow-cljs -A:f3-dev:rad-dev watch main
# in another terminal
$ clj -A:dev:f3-dev:rad-dev:datomic
-----

In IntelliJ, you'd simply make sure to run a CLJ REPL with current classpath, and use the alias checkboxes and `+` button
in the Clojure Deps tab to set it up.

== Building the SPA

You must compile the CLJS source to run the client. If you want to be
able to edit it, just start a shadow-cljs watch:

[source, bash]
-----
$ yarn
$ shadow-cljs watch main
-----

if you don't have `yarn`, use `npm install` instead.

== Running an SQL-based Server

The example code should work with most SQL databases (and defaults to using an in-memory H2 db). The data source
is configured in the `defaults.edn` config file in the sql source
directory. See the HikariCP connection pool documentation.

The SQL example has a custom `development` namespace in the `src/sql` source
folder, along with components needed to run that server.

You can start the server-side version for SQL using the deps aliases that
set up the proper classpath:

[source, bash]
-----
$ clj -A:dev:sql
user=> (clojure.core/require 'development)
user=> (development/go)
-----

== Running a Datomic-based Server

The example code for Datomic components is in the `src/datomic` folder, along with a custom
`development.clj`. It defaults to using an in-memory datomic-free database.

You can run it with the `:datomic` deps alias:

[source, bash]
-----
$ clj -A:dev:datomic
user=> (clojure.core/require 'development)
user=> (development/go)
-----

== Running a Datomic Cloud-based Server
The demo is setup to use an in-memory mock database, so you can be up and running quickly.

The example code for Datomic Cloud components is in the `src/cloud` folder, along with a custom
`development.clj`.

You can run it with the `:cloud` deps alias:

[source, bash]
-----
$ clj -A:dev:cloud
user=> (clojure.core/require 'development)
user=> (development/go)
-----


CAUTION: This in memory mock database uses Datomic Peer under the hood, so some Datalog features
which are not supported on Datomic Cloud will still work using the mock db - only to break when you
try to run against a real Datomic Cloud database!  A good example is the `:find` specification, where
Cloud only supports a limited subset of bindings. Compare the `com.example.components.database-queries`
namespace in the `datomic` and `cloud` source folders to see the difference in queries.

=== Running on a real Datomic Cloud instance
To run on a real version of Datomic Cloud instead of the mock database, you need to:

- Have an installation of Datomic Cloud (Solo topology is fine).  If you haven't used Datomic Cloud before, I recommend you go through the tutorial to make sure your system is configured and working correctly before attempting to run this demo.
- Modify `src/shared/config/default.edn` and change the value of `:datomic/client` from `:mock` to a map containing your
client configuration.  This configuration is passed directly to Datomic and should follow the https://docs.datomic.com/client-api/datomic.client.api.html#var-client[documented configuration].
- Start the Datomic access gateway proxy
- Start the demo using the same steps as in the previous section

==== Example client configuration
[source, edn]
-----
:com.fulcrologic.rad.database-adapters.datomic-cloud/databases
    {:main {:datomic/schema     :production
            :datomic/database   "rad-demo"
            :datomic/client
              {:server-type :ion
               :region "us-east-1"
               :system "my-datomic-system"
               :endpoint "http://entry.my-datomic-system.us-east-1.datomic.net:8182/"
               :proxy-port 8182}}}

-----


== Restarting

The `development/restart` will stop the server, reload source, and start the server.
