= Fulcro RAD Demo (Datomic Cloud Version)

This is a demo repository for Fulcro RAD running on Datomic Cloud.

To run the demo on Datomic on-prem or different datastore, see the `master` branch of this repository.

IMPORTANT: Login is `tony@example.com` with password `letmein`.

== Using dev-local

By default, this demo assumes you are using the link:https://docs.datomic.com/cloud/dev-local.html[dev-local]
library.  `dev-local` is not a maven resource, and must be installed individually. See the link for installation instructions.

If you are using a newer version of the library than the one specified in `deps.edn`, you'll need to update
`deps.edn` with the appropriate version.


== Building the SPA

You must compile the CLJS source to run the client. If you want to be
able to edit it, just start a shadow-cljs watch:

[source, bash]
-----
$ yarn
$ shadow-cljs watch main
-----

if you don't have `yarn`, use `npm install` instead.

== Running a Datomic-based Server

The example code for Datomic components is in the `src/datomic` folder, along with a custom
`development.clj`. It defaults to using an in-memory datomic-free database.

You can run it with the `:datomic` deps alias:

[source, bash]
-----
$ clj -A:dev:datomic
user=> (clojure.core/require 'development)
user=> (development/go)
-----

== Restarting

The `development/restart` will stop the server, reload source, and start the server.

== LICENSE

The MIT License (MIT)
Copyright (c), Fulcrologic, LLC

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
