= Fulcro RAD Demo

This is a demo repository for Fulcro RAD. It includes a shared source directory of files that would be
common to any project, and then separate source directories that have specific files that would be
needed to work with specific back-end technologies (currently SQL and Datomic).

IMPORTANT: Login is `tony@example.com` with password `letmein`.

== Building the SPA

You must compile the CLJS source to run the client. If you want to be
able to edit it, just start a shadow-cljs watch:

[source, bash]
-----
$ yarn
$ shadow-cljs watch main
-----

if you don't have `yarn`, use `npm install` instead.

== Running an SQL-based Server

The example code should work with most SQL databases (and defaults to using an in-memory H2 db). The data source
is configured in the `defaults.edn` config file in the sql source
directory. See the HikariCP connection pool documentation.

The SQL example has a custom `development` namespace in the `src/sql` source
folder, along with components needed to run that server.

You can start the server-side version for SQL using the deps aliases that
set up the proper classpath:

[source, bash]
-----
$ clj -A:dev:sql
user=> (clojure.core/require 'development)
user=> (development/go)
-----

== Running a Datomic-based Server

The example code for Datomic components is in the `src/datomic` folder, along with a custom
`development.clj`. It defaults to using an in-memory datomic-free database.

You can run it with the `:datomic` deps alias:

[source, bash]
-----
$ clj -A:dev:datomic
user=> (clojure.core/require 'development)
user=> (development/go)
-----

== Restarting

The `development/restart` will stop the server, reload source, and start the server.
